parameters:
    darvin_utils.anti_spam.form_type.class: Darvin\Utils\Form\Type\AntiSpamType

services:
    darvin_utils.anti_spam.form_type:
        class: %darvin_utils.anti_spam.form_type.class%
        tags:
            - { name: form.type, alias: darvin_utils_anti_spam }
