parameters:
    darvin_utils.cloner.class: Darvin\Utils\Cloner\Cloner

services:
    _defaults:
        public: true

    darvin_utils.cloner:
        class: "%darvin_utils.cloner.class%"
        arguments:
            - "@event_dispatcher"
            - "@darvin_utils.mapping.metadata_factory"
            - "@property_accessor"
