parameters:
    darvin_utils.cloner.class: Darvin\Utils\Cloner\Cloner

services:
    darvin_utils.cloner:
        class: %darvin_utils.cloner.class%
        arguments:
            - "@event_dispatcher"
            - "@darvin_utils.mapping.metadata_factory"
            - "@property_accessor"
