parameters:
    darvin_utils.default_value.subscriber.class: Darvin\Utils\EventListener\DefaultValueSubscriber

services:
    darvin_utils.default_value.subscriber:
        class: %darvin_utils.default_value.subscriber.class%
        arguments:
            - "@darvin_utils.mapping.metadata_factory"
            - "@property_accessor"
        tags:
            - { name: doctrine.event_subscriber, priority: 500 }
