parameters:
    darvin_utils.default_value.subscriber.class: Darvin\Utils\EventListener\DefaultValueSubscriber

services:
    _defaults:
        public: true

    darvin_utils.default_value.subscriber:
        class:  "%darvin_utils.default_value.subscriber.class%"
        public: false
        arguments:
            - "@darvin_utils.mapping.metadata_factory"
            - "@property_accessor"
        tags:
            - { name: doctrine.event_subscriber, priority: 500 }
