parameters:
    darvin_utils.doctrine.orm.entity_manager_provider.class: Darvin\UtilsBundle\Doctrine\ORM\EntityManagerProvider

services:
    darvin_utils.doctrine.orm.entity_manager_provider:
        class: "%darvin_utils.doctrine.orm.entity_manager_provider.class%"
        arguments:
            - "@service_container"

    darvin_utils.doctrine.object_manager_provider:
        alias: darvin_utils.doctrine.orm.entity_manager_provider
