parameters:
    darvin_utils.form.integer_type_extension.class: Darvin\Utils\Form\Extension\IntegerTypeExtension

    darvin_utils.form.number_type_extension.class: Darvin\Utils\Form\Extension\NumberTypeExtension

services:
    _defaults:
        public: true

    darvin_utils.form.integer_type_extension:
        class: "%darvin_utils.form.integer_type_extension.class%"
        tags:
            - { name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\IntegerType }

    darvin_utils.form.number_type_extension:
        class: "%darvin_utils.form.number_type_extension.class%"
        tags:
            - { name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\NumberType }
