parameters:
    darvin_utils.locale.provider.class: Darvin\Utils\Locale\LocaleProvider

services:
    darvin_utils.locale.provider:
        class:  "%darvin_utils.locale.provider.class%"
        public: true
        arguments:
            - "@request_stack"
            - "%locale%"
