parameters:
    darvin_utils.mailer.class: Darvin\Utils\Mailer\Mailer

services:
    _defaults:
        public: true

    darvin_utils.mailer:
        class: "%darvin_utils.mailer.class%"
        arguments:
            - "@logger"
            - "@request_stack"
            - "@translator"
            - "%darvin_utils.mailer.defaults%"
            - "%darvin_utils.mailer.add_host%"
            - "%darvin_utils.mailer.from.email%"
            - "%darvin_utils.mailer.from.name%"
            - "@mailer"
