parameters:
    darvin_utils.mailer.class: Darvin\Utils\Mailer\Mailer

    darvin_utils.mailer.translation_domain: email

services:
    _defaults:
        public: true

    darvin_utils.mailer:
        class: "%darvin_utils.mailer.class%"
        arguments:
            - "@logger"
            - "@request_stack"
            - "@translator"
            - "%darvin_utils.mailer.translation_domain%"
            - "%darvin_utils.mailer.charset%"
            - "%darvin_utils.mailer.from%"
            - "%darvin_utils.mailer.from_name%"
            - "%darvin_utils.mailer.prepend_host%"
            - "@?mailer"
