parameters:
    darvin_utils.mapping.annotation_driver.abstract.class: Darvin\Utils\Mapping\AnnotationDriver\AbstractDriver

    darvin_utils.mapping.annotation_driver.clonable.class: Darvin\Utils\Mapping\AnnotationDriver\ClonableDriver

    darvin_utils.mapping.annotation_driver.custom_object.class: Darvin\Utils\Mapping\AnnotationDriver\CustomObjectDriver

    darvin_utils.mapping.annotation_driver.default_value.class: Darvin\Utils\Mapping\AnnotationDriver\DefaultValueDriver

    darvin_utils.mapping.annotation_driver.new_object_flag.class: Darvin\Utils\Mapping\AnnotationDriver\NewObjectFlagDriver

    darvin_utils.mapping.annotation_driver.slug.class: Darvin\Utils\Mapping\AnnotationDriver\SlugDriver

    darvin_utils.mapping.annotation_driver.transliteratable.class: Darvin\Utils\Mapping\AnnotationDriver\TransliteratableDriver

    darvin_utils.mapping.annotation_driver.updated_at.class: Darvin\Utils\Mapping\AnnotationDriver\UpdatedAtDriver

    darvin_utils.mapping.annotation_driver.user.class: Darvin\Utils\Mapping\AnnotationDriver\UserDriver

    darvin_utils.mapping.metadata_factory.class: Darvin\Utils\Mapping\MetadataFactory

services:
    darvin_utils.mapping.annotation_driver.abstract:
        class:    "%darvin_utils.mapping.annotation_driver.abstract.class%"
        abstract: true
        public:   false
        arguments:
            - "@annotation_reader"

    darvin_utils.mapping.annotation_driver.clonable:
        class:  "%darvin_utils.mapping.annotation_driver.clonable.class%"
        parent: darvin_utils.mapping.annotation_driver.abstract
        tags:
            - { name: darvin_utils.annotation_driver }

    darvin_utils.mapping.annotation_driver.custom_object:
        class:  "%darvin_utils.mapping.annotation_driver.custom_object.class%"
        parent: darvin_utils.mapping.annotation_driver.abstract
        tags:
            - { name: darvin_utils.annotation_driver }

    darvin_utils.mapping.annotation_driver.default_value:
        class:  "%darvin_utils.mapping.annotation_driver.default_value.class%"
        parent: darvin_utils.mapping.annotation_driver.abstract
        tags:
            - { name: darvin_utils.annotation_driver }

    darvin_utils.mapping.annotation_driver.new_object_flag:
        class:  "%darvin_utils.mapping.annotation_driver.new_object_flag.class%"
        parent: darvin_utils.mapping.annotation_driver.abstract
        tags:
            - { name: darvin_utils.annotation_driver }

    darvin_utils.mapping.annotation_driver.slug:
        class:  "%darvin_utils.mapping.annotation_driver.slug.class%"
        parent: darvin_utils.mapping.annotation_driver.abstract
        tags:
            - { name: darvin_utils.annotation_driver }

    darvin_utils.mapping.annotation_driver.transliteratable:
        class:  "%darvin_utils.mapping.annotation_driver.transliteratable.class%"
        parent: darvin_utils.mapping.annotation_driver.abstract
        tags:
            - { name: darvin_utils.annotation_driver }

    darvin_utils.mapping.annotation_driver.updated_at:
        class:  "%darvin_utils.mapping.annotation_driver.updated_at.class%"
        parent: darvin_utils.mapping.annotation_driver.abstract
        tags:
            - { name: darvin_utils.annotation_driver }

    darvin_utils.mapping.annotation_driver.user:
        class:  "%darvin_utils.mapping.annotation_driver.user.class%"
        parent: darvin_utils.mapping.annotation_driver.abstract
        tags:
            - { name: darvin_utils.annotation_driver }

    darvin_utils.mapping.metadata_factory:
        class: "%darvin_utils.mapping.metadata_factory.class%"
        arguments:
            - "@darvin_utils.object_manager.provider"
