parameters:
    darvin_utils.new_object.counter.entity.class: Darvin\Utils\NewObject\NewEntityCounter

services:
    _defaults:
        public: true

    darvin_utils.new_object.counter:
        alias: darvin_utils.new_object.counter.entity

    darvin_utils.new_object.counter.entity:
        class: "%darvin_utils.new_object.counter.entity.class%"
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@darvin_utils.mapping.metadata_factory"
            - "@darvin_utils.user.query_builder_filterer"
