parameters:
    darvin_utils.orm.entity_resolver.class: Darvin\Utils\ORM\EntityResolver

services:
    darvin_utils.orm.entity_resolver:
        class:  '%darvin_utils.orm.entity_resolver.class%'
        public: true
