parameters:
    darvin_utils.security.authorization_checker_provider.class: Darvin\UtilsBundle\Security\Authorization\AuthorizationCheckerProvider

services:
    darvin_utils.security.authorization_checker_provider:
        class: %darvin_utils.security.authorization_checker_provider.class%
        arguments:
            - "@service_container"
