parameters:
    darvin_utils.service.abstract_provider.class: Darvin\Utils\Service\ServiceProvider

services:
    darvin_utils.service.abstract_provider:
        class:    "%darvin_utils.service.abstract_provider.class%"
        abstract: true
        public:   false
        calls:
            - [ setContainer, [ "@service_container" ] ]
