parameters:
    darvin_utils.sluggable.manager.entity.class: Darvin\Utils\Sluggable\SluggableEntityManager

    darvin_utils.sluggable.subscriber.class: Darvin\Utils\EventListener\SluggableSubscriber

services:
    darvin_utils.sluggable.manager:
        alias: darvin_utils.sluggable.manager.entity

    darvin_utils.sluggable.manager.entity:
        class: %darvin_utils.sluggable.manager.entity.class%
        arguments:
            - "@service_container"
            - "@darvin_utils.doctrine.orm.entity_manager_provider"
            - "@event_dispatcher"
            - "@darvin_utils.mapping.metadata_factory"
            - "@property_accessor"

    darvin_utils.sluggable.subscriber:
        class:  %darvin_utils.sluggable.subscriber.class%
        public: false
        arguments:
            - "@darvin_utils.sluggable.manager"
        tags:
            - { name: doctrine.event_subscriber, priority: 200 }
