parameters:
    darvin_utils.slug.subscriber.class: Darvin\Utils\EventListener\SlugSubscriber

services:
    darvin_utils.slug.subscriber:
        class: %darvin_utils.slug.subscriber.class%
        arguments:
            - "@event_dispatcher"
            - "@darvin_utils.mapping.metadata_factory"
            - "@property_accessor"
        tags:
            - { name: doctrine.event_subscriber, priority: 200 }
