parameters:
    darvin_utils.stringifier.doctrine.class: Darvin\Utils\Strings\Stringifier\DoctrineStringifier

services:
    darvin_utils.stringifier.doctrine:
        class: %darvin_utils.stringifier.doctrine.class%
        arguments:
            - "@translator"
