parameters:
    darvin_utils.templating.provider.class: Darvin\UtilsBundle\Templating\TemplatingProvider

services:
    darvin_utils.templating.provider:
        class: %darvin_utils.templating.provider.class%
        arguments:
            - "@service_container"
