parameters:
    darvin_utils.transliteratable.subscriber.class: Darvin\Utils\EventListener\TransliteratableSubscriber

    darvin_utils.transliteratable.transliterator.class: Darvin\Utils\Transliteratable\DarvinTransliterator

services:
    darvin_utils.transliteratable.subscriber:
        class:  "%darvin_utils.transliteratable.subscriber.class%"
        public: false
        arguments:
            - "@darvin_utils.mapping.metadata_factory"
            - "@property_accessor"
            - "@darvin_utils.transliteratable.transliterator"
        tags:
            - { name: doctrine.event_subscriber, priority: 300 }

    darvin_utils.transliteratable.transliterator:
        class: "%darvin_utils.transliteratable.transliterator.class%"
