parameters:
    darvin_utils.transliteratable.transliterate_event_subscriber.class: Darvin\Utils\EventListener\TransliterateSubscriber

    darvin_utils.transliteratable.transliterator.class: Darvin\Utils\Transliteratable\Transliterator

services:
    _defaults:
        public: true

    darvin_utils.transliteratable.transliterate_event_subscriber:
        class:  '%darvin_utils.transliteratable.transliterate_event_subscriber.class%'
        public: false
        arguments:
            - '@darvin_utils.mapping.metadata_factory'
            - '@property_accessor'
            - '@darvin_utils.transliteratable.transliterator'
        tags:
            - { name: doctrine.event_subscriber, priority: 300 }

    darvin_utils.transliteratable.transliterator:
        class: '%darvin_utils.transliteratable.transliterator.class%'
