parameters:
    darvin_utils.transliteratable.subscriber.class: Darvin\Utils\EventListener\TransliteratableSubscriber

    darvin_utils.transliteratable.transliterator.default.class: Darvin\Utils\Transliteratable\DefaultTransliterator

    darvin_utils.transliteratable.transliterator.strict.class: Darvin\Utils\Transliteratable\StrictTransliterator

services:
    _defaults:
        public: true

    darvin_utils.transliteratable.subscriber:
        class:  "%darvin_utils.transliteratable.subscriber.class%"
        public: false
        arguments:
            - "@darvin_utils.mapping.metadata_factory"
            - "@property_accessor"
            - "@darvin_utils.transliteratable.transliterator"
        tags:
            - { name: doctrine.event_subscriber, priority: 300 }

    darvin_utils.transliteratable.transliterator.default:
        class:  "%darvin_utils.transliteratable.transliterator.default.class%"
        public: false

    darvin_utils.transliteratable.transliterator.strict:
        class:  "%darvin_utils.transliteratable.transliterator.strict.class%"
        public: false
