parameters:
    darvin_utils.homepage.provider.dummy.class: Darvin\Utils\Homepage\DummyHomepageProvider

    darvin_utils.homepage.router.dummy.class: Darvin\Utils\Homepage\DummyHomepageRouter

services:
    Darvin\Utils\Homepage\HomepageProviderInterface: '@darvin_utils.homepage.provider'
    Darvin\Utils\Homepage\HomepageRouterInterface:   '@darvin_utils.homepage.router'

    darvin_utils.homepage.provider:
        alias: darvin_utils.homepage.provider.dummy

    darvin_utils.homepage.provider.dummy:
        class: '%darvin_utils.homepage.provider.dummy.class%'

    darvin_utils.homepage.router:
        alias: darvin_utils.homepage.router.dummy

    darvin_utils.homepage.router.dummy:
        class: '%darvin_utils.homepage.router.dummy.class%'
