parameters:
    darvin_utils.homepage.dummy_provider.class: Darvin\Utils\Homepage\DummyHomepageProvider

    darvin_utils.homepage.dummy_router.class: Darvin\Utils\Homepage\DummyHomepageRouter

services:
    Darvin\Utils\Homepage\HomepageProviderInterface: '@darvin_utils.homepage.provider'
    Darvin\Utils\Homepage\HomepageRouterInterface:   '@darvin_utils.homepage.router'

    darvin_utils.homepage.provider:
        alias: darvin_utils.homepage.dummy_provider

    darvin_utils.homepage.dummy_provider:
        class: '%darvin_utils.homepage.dummy_provider.class%'

    darvin_utils.homepage.router:
        alias: darvin_utils.homepage.dummy_router

    darvin_utils.homepage.dummy_router:
        class: '%darvin_utils.homepage.dummy_router.class%'
