parameters:
    darvin_utils.object_namer.class: Darvin\Utils\ObjectNamer\ObjectNamer

    darvin_utils.object_namer.twig_extension.class: Darvin\Utils\Twig\Extension\ObjectNamerExtension

services:
    darvin_utils.object_namer:
        class: "%darvin_utils.object_namer.class%"

    darvin_utils.object_namer.twig_extension:
        class: "%darvin_utils.object_namer.twig_extension.class%"
        arguments:
            - "@darvin_utils.object_namer"
        tags:
            - { name: twig.extension }
