parameters:
    darvin_utils.price.formatter.class: Darvin\UtilsBundle\Price\PriceFormatter

    darvin_utils.price.twig_extension.class: Darvin\Utils\Twig\Extension\PriceExtension

services:
    Darvin\Utils\Price\PriceFormatterInterface: '@darvin_utils.price.formatter'

    darvin_utils.price.formatter:
        class: '%darvin_utils.price.formatter.class%'
        arguments:
            - '@darvin_utils.twig.provider'

    darvin_utils.price.twig_extension:
        class: '%darvin_utils.price.twig_extension.class%'
        arguments:
            - '@darvin_utils.price.formatter'
        tags:
            - { name: twig.extension }
