parameters:
    darvin_utils.routing.route_cache_warmer.class: Darvin\Utils\Routing\RouteCacheWarmer

    darvin_utils.routing.route_manager.cached.class: Darvin\Utils\Routing\CachedRouteManager

services:
    darvin_utils.routing.route_cache_warmer:
        class: '%darvin_utils.routing.route_cache_warmer.class%'
        arguments:
            - '@darvin_utils.routing.route_manager.cached'
        tags:
            - { name: kernel.cache_warmer }

    darvin_utils.routing.route_manager:
        alias: darvin_utils.routing.route_manager.cached

    darvin_utils.routing.route_manager.cached:
        class: '%darvin_utils.routing.route_manager.cached.class%'
        arguments:
            - '@darvin_utils.locale.provider'
            - '@router.default'
            - '%kernel.cache_dir%/darvin_utils/routes.php'
            - '%kernel.debug%'
            - '%locales%'
