parameters:
    darvin_utils.security.accessibility_checker.class: Darvin\Utils\Security\Authorization\AccessibilityChecker

services:
    Darvin\Utils\Security\Authorization\AccessibilityCheckerInterface: '@darvin_utils.security.accessibility_checker'

    darvin_utils.security.accessibility_checker:
        class: '%darvin_utils.security.accessibility_checker.class%'
        arguments:
            - '@darvin_utils.authorization_checker.provider'
