parameters:
    darvin_utils.sluggable.manager.entity.class: Darvin\Utils\Sluggable\SluggableEntityManager

    darvin_utils.sluggable.slugify_event_subscriber.class: Darvin\Utils\EventListener\SlugifySubscriber

services:
    Darvin\Utils\Sluggable\SluggableManagerInterface: '@darvin_utils.sluggable.manager.entity'

    darvin_utils.sluggable.manager:
        alias: darvin_utils.sluggable.manager.entity

    darvin_utils.sluggable.manager.entity:
        class: '%darvin_utils.sluggable.manager.entity.class%'
        arguments:
            - '@darvin_utils.entity_manager.provider'
            - '@event_dispatcher'
            - '@darvin_utils.mapping.metadata_factory'
            - '@property_accessor'

    darvin_utils.sluggable.slugify_event_subscriber:
        class: '%darvin_utils.sluggable.slugify_event_subscriber.class%'
        arguments:
            - '@darvin_utils.entity_manager.provider'
            - '@darvin_utils.sluggable.manager'
        tags:
            - { name: doctrine.event_subscriber, priority: 200 }
