parameters:
    darvin_utils.user.query_builder_filterer.class: Darvin\Utils\User\UserQueryBuilderFilterer

services:
    Darvin\Utils\User\UserQueryBuilderFiltererInterface: '@darvin_utils.user.query_builder_filterer'

    darvin_utils.user.query_builder_filterer:
        class: '%darvin_utils.user.query_builder_filterer.class%'
        arguments:
            - '@security.token_storage'
            - '@security.authorization_checker'
            - '@darvin_utils.mapping.metadata_factory'
