parameters:
    darvin_utils.view.data.factory.class: Darvin\Utils\View\Data\Factory\DataViewFactory

services:
    Darvin\Utils\View\Data\Factory\DataViewFactoryInterface: '@darvin_utils.view.data.factory'

    darvin_utils.view.data.factory:
        class: '%darvin_utils.view.data.factory.class%'
        arguments:
            - '@darvin_utils.stringifier'
