parameters:
    darvin_utils.override.command.class: Darvin\Utils\Command\OverrideCommand
    darvin_utils.override.command.name:  darvin:utils:override

    darvin_utils.override.config.class: Darvin\Utils\Override\Config\OverrideConfig

    darvin_utils.override.overrider.entity.class: Darvin\Utils\Override\Overrider\EntityOverrider

    darvin_utils.override.overrider.template.class: Darvin\Utils\Override\Overrider\TemplateOverrider

    darvin_utils.override.overrider_pool.class: Darvin\Utils\Override\OverriderPool

services:
    darvin_utils.override.command:
        class: '%darvin_utils.override.command.class%'
        arguments:
            - '%darvin_utils.override.command.name%'
            - '@darvin_utils.override.overrider_pool'
        tags:
            - { name: console.command }

    darvin_utils.override.config:
        class: '%darvin_utils.override.config.class%'
        arguments:
            - '%darvin_utils.override%'

    darvin_utils.override.overrider.entity:
        class: '%darvin_utils.override.overrider.entity.class%'
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@filesystem'
            - '@darvin_content.translatable.manager'
            - '@twig'
            - '%kernel.bundles_metadata%'
            - '%kernel.project_dir%'
        tags:
            - { name: darvin_utils.overrider }

    darvin_utils.override.overrider.template:
        class: '%darvin_utils.override.overrider.template.class%'
        arguments:
            - '@filesystem'
            - '%kernel.bundles_metadata%'
            - '%kernel.project_dir%'
        tags:
            - { name: darvin_utils.overrider }

    darvin_utils.override.overrider_pool:
        class: '%darvin_utils.override.overrider_pool.class%'
        arguments:
            - '@darvin_utils.override.config'
