parameters:
    darvin_utils.response.compress.subscriber.class: Darvin\Utils\EventListener\CompressResponseSubscriber

services:
    darvin_utils.response.compress.subscriber:
        class: '%darvin_utils.response.compress.subscriber.class%'
        tags:
            - { name: kernel.event_subscriber }
